// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, OcrScanData, OcrScanResponse, PrivateCreateUserData, PrivateCreateUserResponse, ProfileReadProfilesData, ProfileReadProfilesResponse, ProfileReadProfileMeResponse, ProfileCreateProfileMeData, ProfileCreateProfileMeResponse, ProfileUpdateProfileMeData, ProfileUpdateProfileMeResponse, ProfileCreateProfileData, ProfileCreateProfileResponse, ProfileUpdateProfileData, ProfileUpdateProfileResponse, ReceiptReadReceiptsData, ReceiptReadReceiptsResponse, ReceiptUpdateReceiptData, ReceiptUpdateReceiptResponse, ReceiptReadReceiptsMeData, ReceiptReadReceiptsMeResponse, ReceiptCreateReceiptData, ReceiptCreateReceiptResponse, ReceiptDeleteReceiptData, ReceiptDeleteReceiptResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class OcrService {
    /**
     * Scan
     * @param data The data for the request.
     * @param data.formData
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static scan(data: OcrScanData): CancelablePromise<OcrScanResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/ocr/scan',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ProfileService {
    /**
     * Read Profiles
     * Retrieve profiles.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ProfilesPublic Successful Response
     * @throws ApiError
     */
    public static readProfiles(data: ProfileReadProfilesData = {}): CancelablePromise<ProfileReadProfilesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/profile/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Profile Me
     * Retrieve profiles.
     * @returns ProfilePublic Successful Response
     * @throws ApiError
     */
    public static readProfileMe(): CancelablePromise<ProfileReadProfileMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/profile/me'
        });
    }
    
    /**
     * Create Profile Me
     * Create my new profile.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ProfilePublic Successful Response
     * @throws ApiError
     */
    public static createProfileMe(data: ProfileCreateProfileMeData): CancelablePromise<ProfileCreateProfileMeResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/profile/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Profile Me
     * Update own profile.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ProfilePublic Successful Response
     * @throws ApiError
     */
    public static updateProfileMe(data: ProfileUpdateProfileMeData): CancelablePromise<ProfileUpdateProfileMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/profile/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Profile
     * Create new profile.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns ProfilePublic Successful Response
     * @throws ApiError
     */
    public static createProfile(data: ProfileCreateProfileData): CancelablePromise<ProfileCreateProfileResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/profile/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Profile
     * Update user profile.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns ProfilePublic Successful Response
     * @throws ApiError
     */
    public static updateProfile(data: ProfileUpdateProfileData): CancelablePromise<ProfileUpdateProfileResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/profile/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ReceiptService {
    /**
     * Read Receipts
     * Retrieve all receipts with optional search and filtering.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.q
     * @param data.dateFrom
     * @param data.dateTo
     * @returns ReceiptsPublicDetailed Successful Response
     * @throws ApiError
     */
    public static readReceipts(data: ReceiptReadReceiptsData = {}): CancelablePromise<ReceiptReadReceiptsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/receipt/',
            query: {
                skip: data.skip,
                limit: data.limit,
                q: data.q,
                date_from: data.dateFrom,
                date_to: data.dateTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Receipt
     * Update the user receipt with receipt_id.
     * @param data The data for the request.
     * @param data.receiptId
     * @param data.requestBody
     * @returns ReceiptPublic Successful Response
     * @throws ApiError
     */
    public static updateReceipt(data: ReceiptUpdateReceiptData): CancelablePromise<ReceiptUpdateReceiptResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/receipt/',
            query: {
                receipt_id: data.receiptId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Receipts Me
     * Retrieve current user receipts with optional search and filtering.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.q
     * @param data.dateFrom
     * @param data.dateTo
     * @returns ReceiptsPublicDetailedMe Successful Response
     * @throws ApiError
     */
    public static readReceiptsMe(data: ReceiptReadReceiptsMeData = {}): CancelablePromise<ReceiptReadReceiptsMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/receipt/me',
            query: {
                skip: data.skip,
                limit: data.limit,
                q: data.q,
                date_from: data.dateFrom,
                date_to: data.dateTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Receipt
     * Create my new receipt.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ReceiptPublic Successful Response
     * @throws ApiError
     */
    public static createReceipt(data: ReceiptCreateReceiptData): CancelablePromise<ReceiptCreateReceiptResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/receipt/create',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Receipt
     * @param data The data for the request.
     * @param data.receiptId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static deleteReceipt(data: ReceiptDeleteReceiptData): CancelablePromise<ReceiptDeleteReceiptResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/receipt/{receipt_id}',
            path: {
                receipt_id: data.receiptId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.query
     * @returns UsersPublicWithProfile Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit,
                query: data.query
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublicWithProfile Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}