// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_ocr_scan = {
    img_file: (Blob | File);
};

export type BranchPublicWithStore = {
    address?: (string | null);
    city?: (string | null);
    id: string;
    store: StorePublic;
};

export type BranchReceiptIn = {
    address?: (string | null);
    city?: (string | null);
};

export type CurrencyEnum = 'USD' | 'EUR' | 'BAM' | 'GBP';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProfileCreate = {
    first_name: string;
    last_name: string;
    phone_number?: (string | null);
    date_of_birth?: (string | null);
    country?: (string | null);
    address?: (string | null);
    city?: (string | null);
    currency_preference?: CurrencyEnum;
};

export type ProfileCreateMe = {
    first_name: string;
    last_name: string;
    phone_number?: (string | null);
    date_of_birth?: (string | null);
    country?: (string | null);
    address?: (string | null);
    city?: (string | null);
    currency_preference?: CurrencyEnum;
};

export type ProfilePublic = {
    first_name: string;
    last_name: string;
    phone_number?: (string | null);
    date_of_birth?: (string | null);
    country?: (string | null);
    address?: (string | null);
    city?: (string | null);
    currency_preference?: CurrencyEnum;
    id: string;
    user_id: string;
};

export type ProfilesPublic = {
    data: Array<ProfilePublic>;
    count: number;
};

export type ProfileUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    phone_number?: (string | null);
    date_of_birth?: (string | null);
    country?: (string | null);
    address?: (string | null);
    city?: (string | null);
    currency_preference?: (string | null);
    updated_at?: string;
};

export type ReceiptCreate = {
    date_time?: string;
    tax_amount?: (number | null);
    total_amount?: (number | null);
    payment_method?: (string | null);
    currency?: CurrencyEnum;
    store: StoreReceiptIn;
    branch: BranchReceiptIn;
    details: ReceiptDetailsReceiptIn;
    items: Array<ReceiptItemCreate>;
};

export type ReceiptDetailsPublic = {
    ibfm?: (string | null);
    bf?: (number | null);
    id: string;
};

export type ReceiptDetailsReceiptIn = {
    ibfm?: (string | null);
    bf?: (number | null);
};

export type ReceiptItemCreate = {
    name: string;
    quantity?: number;
    price: number;
    total_price: number;
};

export type ReceiptItemPublic = {
    name: string;
    quantity?: number;
    price: number;
    total_price: number;
    id: string;
};

export type ReceiptPublic = {
    date_time?: string;
    tax_amount?: (number | null);
    total_amount?: (number | null);
    payment_method?: (string | null);
    currency?: CurrencyEnum;
    id: string;
    created_at: string;
    updated_at: string;
};

export type ReceiptPublicDetailed = {
    date_time?: string;
    tax_amount?: (number | null);
    total_amount?: (number | null);
    payment_method?: (string | null);
    currency?: CurrencyEnum;
    id: string;
    created_at: string;
    updated_at: string;
    details: ReceiptDetailsPublic;
    items?: Array<ReceiptItemPublic>;
    branch: BranchPublicWithStore;
    user: UserPublicWithProfile;
};

export type ReceiptPublicDetailedMe = {
    date_time?: string;
    tax_amount?: (number | null);
    total_amount?: (number | null);
    payment_method?: (string | null);
    currency?: CurrencyEnum;
    id: string;
    created_at: string;
    updated_at: string;
    items?: Array<ReceiptItemPublic>;
    branch: BranchPublicWithStore;
};

export type ReceiptsPublicDetailed = {
    data: Array<ReceiptPublicDetailed>;
    count: number;
};

export type ReceiptsPublicDetailedMe = {
    data: Array<ReceiptPublicDetailedMe>;
    count: number;
};

export type ReceiptUpdate = {
    date_time?: (string | null);
    tax?: (number | null);
    total_price?: (number | null);
    payment_method?: (string | null);
    currency: (CurrencyEnum | null);
    updated_at?: string;
};

export type StorePublic = {
    name: string;
    jib?: (string | null);
    pib?: (string | null);
    id: string;
};

export type StoreReceiptIn = {
    name: string;
    jib?: (string | null);
    pib?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
};

export type UserPublicWithProfile = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
    profile?: (ProfilePublic | null);
};

export type UserRegister = {
    email: string;
    password: string;
};

export type UsersPublicWithProfile = {
    data: Array<UserPublicWithProfile>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    password?: (string | null);
    updated_at?: string;
};

export type UserUpdateMe = {
    email?: (string | null);
    updated_at?: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OcrScanData = {
    formData: Body_ocr_scan;
};

export type OcrScanResponse = (unknown);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProfileReadProfilesData = {
    limit?: number;
    skip?: number;
};

export type ProfileReadProfilesResponse = (ProfilesPublic);

export type ProfileReadProfileMeResponse = (ProfilePublic);

export type ProfileCreateProfileMeData = {
    requestBody: ProfileCreateMe;
};

export type ProfileCreateProfileMeResponse = (ProfilePublic);

export type ProfileUpdateProfileMeData = {
    requestBody: ProfileUpdate;
};

export type ProfileUpdateProfileMeResponse = (ProfilePublic);

export type ProfileCreateProfileData = {
    requestBody: ProfileCreate;
    userId: string;
};

export type ProfileCreateProfileResponse = (ProfilePublic);

export type ProfileUpdateProfileData = {
    requestBody: ProfileUpdate;
    userId: string;
};

export type ProfileUpdateProfileResponse = (ProfilePublic);

export type ReceiptReadReceiptsData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    limit?: number;
    q?: (string | null);
    skip?: number;
};

export type ReceiptReadReceiptsResponse = (ReceiptsPublicDetailed);

export type ReceiptUpdateReceiptData = {
    receiptId: string;
    requestBody: ReceiptUpdate;
};

export type ReceiptUpdateReceiptResponse = (ReceiptPublic);

export type ReceiptReadReceiptsMeData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    limit?: number;
    q?: (string | null);
    skip?: number;
};

export type ReceiptReadReceiptsMeResponse = (ReceiptsPublicDetailedMe);

export type ReceiptCreateReceiptData = {
    requestBody: ReceiptCreate;
};

export type ReceiptCreateReceiptResponse = (ReceiptPublic);

export type ReceiptDeleteReceiptData = {
    receiptId: string;
};

export type ReceiptDeleteReceiptResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    q?: (string | null);
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublicWithProfile);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublicWithProfile);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);