"""fix Receipt and ReceiptItems

Revision ID: 11a8f3bb9258
Revises: 9996d4ae0663
Create Date: 2026-01-06 18:22:27.047946

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '11a8f3bb9258'
down_revision = '9996d4ae0663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
