"""fix receipt details model relationship with receipt

Revision ID: 17d23c06044c
Revises: 8a85b6a39cb5
Create Date: 2026-01-16 04:14:15.550461

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '17d23c06044c'
down_revision = '8a85b6a39cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
