"""fix how datetime is returned

Revision ID: 50287c6cf6a2
Revises: 6f449130046d
Create Date: 2026-01-18 17:37:04.788395

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '50287c6cf6a2'
down_revision = '6f449130046d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
