"""update date fields to use timezones

Revision ID: 6f449130046d
Revises: b0d41ef3926e
Create Date: 2026-01-18 17:08:02.550816

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6f449130046d'
down_revision = 'b0d41ef3926e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
