"""add branch, product, product_price_history

Revision ID: 73a2ed169db1
Revises: b21750b09f11
Create Date: 2025-12-18 12:30:19.558098

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '73a2ed169db1'
down_revision = 'b21750b09f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branch',
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productpricehistory',
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'BAM', 'GBP', name='currencyenum'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receipt_item_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_item_id'], ['receiptitem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('profile', sa.Column('currency_preference', sa.Enum('USD', 'EUR', 'BAM', 'GBP', name='currencyenum'), nullable=False))
    op.add_column('receipt', sa.Column('tax_amount', sa.Float(), nullable=True))
    op.add_column('receipt', sa.Column('total_amount', sa.Float(), nullable=True))
    op.add_column('receipt', sa.Column('currency', sa.Enum('USD', 'EUR', 'BAM', 'GBP', name='currencyenum'), nullable=False))
    op.add_column('receipt', sa.Column('branch_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('receipt_store_id_fkey'), 'receipt', type_='foreignkey')
    op.create_foreign_key(None, 'receipt', 'branch', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_column('receipt', 'store_id')
    op.drop_column('receipt', 'total_price')
    op.drop_column('receipt', 'tax')
    op.drop_column('store', 'city')
    op.drop_column('store', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('store', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('receipt', sa.Column('tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('receipt', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('receipt', sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.create_foreign_key(op.f('receipt_store_id_fkey'), 'receipt', 'store', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_column('receipt', 'branch_id')
    op.drop_column('receipt', 'currency')
    op.drop_column('receipt', 'total_amount')
    op.drop_column('receipt', 'tax_amount')
    op.drop_column('profile', 'currency_preference')
    op.drop_table('productpricehistory')
    op.drop_table('branch')
    op.drop_table('product')
    # ### end Alembic commands ###
