"""remove store relationship, added in last revision, from receipt

Revision ID: 8a85b6a39cb5
Revises: 98219a7afdd6
Create Date: 2026-01-16 04:10:40.500290

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8a85b6a39cb5'
down_revision = '98219a7afdd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
