"""add details to receiptpublicdetailed, remove ibk and digital_signature from receiptdetails

Revision ID: 98219a7afdd6
Revises: 367f78853eba
Create Date: 2026-01-16 04:08:06.884712

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '98219a7afdd6'
down_revision = '367f78853eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receiptdetails', 'digital_signature')
    op.drop_column('receiptdetails', 'ibk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receiptdetails', sa.Column('ibk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('receiptdetails', sa.Column('digital_signature', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
