"""update receipt model

Revision ID: 9996d4ae0663
Revises: a36828720b06
Create Date: 2026-01-05 20:31:00.548320

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9996d4ae0663'
down_revision = 'a36828720b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
