"""add items to receipt model

Revision ID: a36828720b06
Revises: fa8f4f724d7c
Create Date: 2026-01-05 18:31:48.452402

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a36828720b06'
down_revision = 'fa8f4f724d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
