"""restore digital_signature in receipt details

Revision ID: b0d41ef3926e
Revises: 17d23c06044c
Create Date: 2026-01-16 23:39:52.194955

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b0d41ef3926e'
down_revision = '17d23c06044c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receiptdetails', sa.Column('digital_signature', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receiptdetails', 'digital_signature')
    # ### end Alembic commands ###
