"""fix receiptitem

Revision ID: fa8f4f724d7c
Revises: 73a2ed169db1
Create Date: 2026-01-05 18:04:56.065192

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fa8f4f724d7c'
down_revision = '73a2ed169db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c["name"] for c in inspector.get_columns("receiptitem")]
    if "product_id" not in columns:
        op.add_column('receiptitem', sa.Column('product_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'receiptitem', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receiptitem', type_='foreignkey')
    op.drop_column('receiptitem', 'product_id')
    # ### end Alembic commands ###
